### ISSUE TITLE
For PacMan mode, snake starts partly inside wall and can pass through walls if moving fast enough

### ISSUE THREAD

**Issue by schwi1996** [COMP2522/project-redbull#121]
When starting the PacMan mode, the snake has its tail in the wall and when moving, it's segmented. In addition, if moving fast enough, the snake is able to pass through walls and travel for a short distance before it's registered as dead.

<img width="524" alt="snake" src="https://user-images.githubusercontent.com/113309333/228317116-6908d757-caad-4cf1-a5d9-b37825334cf7.png">
<img width="518" alt="snake2" src="https://user-images.githubusercontent.com/113309333/228317679-731465d5-0440-43d5-a8ce-0ec428d8a07a.png">

**Comment by kavindail** [comment]
Moved Spawnpoint - Completed
