### ISSUE TITLE
Consider changing case numbers in Enemy to more meaningful variable names

### ISSUE THREAD

**Issue by schwi1996** [COMP2522/project-redbull#130]
Case numbers are magic numbers, it may be helpful to list them as variable names so that there's more context as to what the cases are.

https://github.com/COMP2522/project-redbull/blob/6073f58c2aa8ff311d83bb5de4f33326128ce3cb/src/main/java/org/Snake/Enemy.java#L35

**Comment by kavindail** [comment]
Completed
