### ISSUE TITLE
Case of Magic Numbers

### ISSUE THREAD

**Issue by ssidhu271** [COMP2522/project-redbull#74]
https://github.com/COMP2522/project-redbull/blob/483f7a7c6a9e588ba99aa3df040df43d23db18e5/src/main/java/org/Snake/Enemy.java#L41

Saw in the enemy class that there are more magic numbers and more in the switch statement. Can fix this by making the instance variable above and calling below for more readability.

**Comment by kavindail** [comment]
Completed
