### ISSUE TITLE
Remove Magic Numbers in InGameUI constructor

### ISSUE THREAD

**Issue by abhishekchouhannk** [COMP2522/project-redbull#97]
https://github.com/COMP2522/project-redbull/blob/483f7a7c6a9e588ba99aa3df040df43d23db18e5/src/main/java/org/Snake/InGameUI.java#L30

Magic numbers in the above line, 

100 repeated and not specified as to what it does, also can't make out what "right" is.

**Comment by kavindail** [comment]
Completed
